version: '3.7'

services:
  hydra:
    image: oryd/hydra:v1.11.7
    platform: "linux/amd64"
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - type: bind
        source: ./etc/config/hydra/
        target: /etc/config/hydra/
    environment:
      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
      - GINGER_URL=http://faux-ginger/index.php/
      - GINGER_KEY=fauxginger
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.11.7
    platform: "linux/amd64"
    environment:
      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./etc/config/hydra/
        target: /etc/config/hydra/
    restart: on-failure
    networks:
      - intranet
    depends_on:
      - mysqld

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - BASE_URL=http://127.0.0.1:3000
      - CAS_URL=https://thecas
    #image: oryd/hydra-login-consent-node:v1.11.7
    build: ./hydra-login-consent-CAS-mysql
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet

  mysqld:
    image: mysql:5.7
    platform: "linux/amd64"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - intranet

  faux-ginger:
    image: php:8.1.5RC1-apache
    ports:
      - "8001:80"
    volumes:
      - type: bind
        source: ./faux-ginger/
        target: /var/www/html/

networks:
  intranet:
